// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPICustomersIDRatesRateIDReader is a Reader for the DeleteAPICustomersIDRatesRateID structure.
type DeleteAPICustomersIDRatesRateIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPICustomersIDRatesRateIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPICustomersIDRatesRateIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPICustomersIDRatesRateIDNoContent creates a DeleteAPICustomersIDRatesRateIDNoContent with default headers values
func NewDeleteAPICustomersIDRatesRateIDNoContent() *DeleteAPICustomersIDRatesRateIDNoContent {
	return &DeleteAPICustomersIDRatesRateIDNoContent{}
}

/*
DeleteAPICustomersIDRatesRateIDNoContent describes a response with status code 204, with default header values.

Returns no content: 204 on successful delete
*/
type DeleteAPICustomersIDRatesRateIDNoContent struct {
}

// IsSuccess returns true when this delete Api customers Id rates rate Id no content response has a 2xx status code
func (o *DeleteAPICustomersIDRatesRateIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api customers Id rates rate Id no content response has a 3xx status code
func (o *DeleteAPICustomersIDRatesRateIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api customers Id rates rate Id no content response has a 4xx status code
func (o *DeleteAPICustomersIDRatesRateIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api customers Id rates rate Id no content response has a 5xx status code
func (o *DeleteAPICustomersIDRatesRateIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api customers Id rates rate Id no content response a status code equal to that given
func (o *DeleteAPICustomersIDRatesRateIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteAPICustomersIDRatesRateIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/customers/{id}/rates/{rateId}][%d] deleteApiCustomersIdRatesRateIdNoContent ", 204)
}

func (o *DeleteAPICustomersIDRatesRateIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/customers/{id}/rates/{rateId}][%d] deleteApiCustomersIdRatesRateIdNoContent ", 204)
}

func (o *DeleteAPICustomersIDRatesRateIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
