// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPICustomersIDRatesRateIDParams creates a new DeleteAPICustomersIDRatesRateIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPICustomersIDRatesRateIDParams() *DeleteAPICustomersIDRatesRateIDParams {
	return &DeleteAPICustomersIDRatesRateIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPICustomersIDRatesRateIDParamsWithTimeout creates a new DeleteAPICustomersIDRatesRateIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPICustomersIDRatesRateIDParamsWithTimeout(timeout time.Duration) *DeleteAPICustomersIDRatesRateIDParams {
	return &DeleteAPICustomersIDRatesRateIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPICustomersIDRatesRateIDParamsWithContext creates a new DeleteAPICustomersIDRatesRateIDParams object
// with the ability to set a context for a request.
func NewDeleteAPICustomersIDRatesRateIDParamsWithContext(ctx context.Context) *DeleteAPICustomersIDRatesRateIDParams {
	return &DeleteAPICustomersIDRatesRateIDParams{
		Context: ctx,
	}
}

// NewDeleteAPICustomersIDRatesRateIDParamsWithHTTPClient creates a new DeleteAPICustomersIDRatesRateIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPICustomersIDRatesRateIDParamsWithHTTPClient(client *http.Client) *DeleteAPICustomersIDRatesRateIDParams {
	return &DeleteAPICustomersIDRatesRateIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPICustomersIDRatesRateIDParams contains all the parameters to send to the API endpoint

	for the delete API customers ID rates rate ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPICustomersIDRatesRateIDParams struct {

	/* ID.

	   The customer whose rate will be removed
	*/
	ID int64

	/* RateID.

	   The rate to remove
	*/
	RateID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API customers ID rates rate ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPICustomersIDRatesRateIDParams) WithDefaults() *DeleteAPICustomersIDRatesRateIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API customers ID rates rate ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPICustomersIDRatesRateIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) WithTimeout(timeout time.Duration) *DeleteAPICustomersIDRatesRateIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) WithContext(ctx context.Context) *DeleteAPICustomersIDRatesRateIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) WithHTTPClient(client *http.Client) *DeleteAPICustomersIDRatesRateIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) WithID(id int64) *DeleteAPICustomersIDRatesRateIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) SetID(id int64) {
	o.ID = id
}

// WithRateID adds the rateID to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) WithRateID(rateID int64) *DeleteAPICustomersIDRatesRateIDParams {
	o.SetRateID(rateID)
	return o
}

// SetRateID adds the rateId to the delete API customers ID rates rate ID params
func (o *DeleteAPICustomersIDRatesRateIDParams) SetRateID(rateID int64) {
	o.RateID = rateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPICustomersIDRatesRateIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param rateId
	if err := r.SetPathParam("rateId", swag.FormatInt64(o.RateID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
