// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchAPICustomersIDMetaParams creates a new PatchAPICustomersIDMetaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPICustomersIDMetaParams() *PatchAPICustomersIDMetaParams {
	return &PatchAPICustomersIDMetaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPICustomersIDMetaParamsWithTimeout creates a new PatchAPICustomersIDMetaParams object
// with the ability to set a timeout on a request.
func NewPatchAPICustomersIDMetaParamsWithTimeout(timeout time.Duration) *PatchAPICustomersIDMetaParams {
	return &PatchAPICustomersIDMetaParams{
		timeout: timeout,
	}
}

// NewPatchAPICustomersIDMetaParamsWithContext creates a new PatchAPICustomersIDMetaParams object
// with the ability to set a context for a request.
func NewPatchAPICustomersIDMetaParamsWithContext(ctx context.Context) *PatchAPICustomersIDMetaParams {
	return &PatchAPICustomersIDMetaParams{
		Context: ctx,
	}
}

// NewPatchAPICustomersIDMetaParamsWithHTTPClient creates a new PatchAPICustomersIDMetaParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPICustomersIDMetaParamsWithHTTPClient(client *http.Client) *PatchAPICustomersIDMetaParams {
	return &PatchAPICustomersIDMetaParams{
		HTTPClient: client,
	}
}

/*
PatchAPICustomersIDMetaParams contains all the parameters to send to the API endpoint

	for the patch API customers ID meta operation.

	Typically these are written to a http.Request.
*/
type PatchAPICustomersIDMetaParams struct {

	// Body.
	Body PatchAPICustomersIDMetaBody

	/* ID.

	   Customer record ID to set the meta-field value for
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API customers ID meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPICustomersIDMetaParams) WithDefaults() *PatchAPICustomersIDMetaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API customers ID meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPICustomersIDMetaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) WithTimeout(timeout time.Duration) *PatchAPICustomersIDMetaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) WithContext(ctx context.Context) *PatchAPICustomersIDMetaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) WithHTTPClient(client *http.Client) *PatchAPICustomersIDMetaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) WithBody(body PatchAPICustomersIDMetaBody) *PatchAPICustomersIDMetaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) SetBody(body PatchAPICustomersIDMetaBody) {
	o.Body = body
}

// WithID adds the id to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) WithID(id int64) *PatchAPICustomersIDMetaParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API customers ID meta params
func (o *PatchAPICustomersIDMetaParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPICustomersIDMetaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
