// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// PostAPICustomersIDRatesReader is a Reader for the PostAPICustomersIDRates structure.
type PostAPICustomersIDRatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPICustomersIDRatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPICustomersIDRatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPICustomersIDRatesOK creates a PostAPICustomersIDRatesOK with default headers values
func NewPostAPICustomersIDRatesOK() *PostAPICustomersIDRatesOK {
	return &PostAPICustomersIDRatesOK{}
}

/*
PostAPICustomersIDRatesOK describes a response with status code 200, with default header values.

Returns the new created rate
*/
type PostAPICustomersIDRatesOK struct {
	Payload *models.CustomerRate
}

// IsSuccess returns true when this post Api customers Id rates o k response has a 2xx status code
func (o *PostAPICustomersIDRatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api customers Id rates o k response has a 3xx status code
func (o *PostAPICustomersIDRatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api customers Id rates o k response has a 4xx status code
func (o *PostAPICustomersIDRatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api customers Id rates o k response has a 5xx status code
func (o *PostAPICustomersIDRatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api customers Id rates o k response a status code equal to that given
func (o *PostAPICustomersIDRatesOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAPICustomersIDRatesOK) Error() string {
	return fmt.Sprintf("[POST /api/customers/{id}/rates][%d] postApiCustomersIdRatesOK  %+v", 200, o.Payload)
}

func (o *PostAPICustomersIDRatesOK) String() string {
	return fmt.Sprintf("[POST /api/customers/{id}/rates][%d] postApiCustomersIdRatesOK  %+v", 200, o.Payload)
}

func (o *PostAPICustomersIDRatesOK) GetPayload() *models.CustomerRate {
	return o.Payload
}

func (o *PostAPICustomersIDRatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerRate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
