// Code generated by go-swagger; DO NOT EDIT.

package expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPIExpensesIDParams creates a new DeleteAPIExpensesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIExpensesIDParams() *DeleteAPIExpensesIDParams {
	return &DeleteAPIExpensesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIExpensesIDParamsWithTimeout creates a new DeleteAPIExpensesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIExpensesIDParamsWithTimeout(timeout time.Duration) *DeleteAPIExpensesIDParams {
	return &DeleteAPIExpensesIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIExpensesIDParamsWithContext creates a new DeleteAPIExpensesIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIExpensesIDParamsWithContext(ctx context.Context) *DeleteAPIExpensesIDParams {
	return &DeleteAPIExpensesIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIExpensesIDParamsWithHTTPClient creates a new DeleteAPIExpensesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIExpensesIDParamsWithHTTPClient(client *http.Client) *DeleteAPIExpensesIDParams {
	return &DeleteAPIExpensesIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIExpensesIDParams contains all the parameters to send to the API endpoint

	for the delete API expenses ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIExpensesIDParams struct {

	/* ID.

	   Expense record ID to delete
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API expenses ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIExpensesIDParams) WithDefaults() *DeleteAPIExpensesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API expenses ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIExpensesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) WithTimeout(timeout time.Duration) *DeleteAPIExpensesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) WithContext(ctx context.Context) *DeleteAPIExpensesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) WithHTTPClient(client *http.Client) *DeleteAPIExpensesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) WithID(id int64) *DeleteAPIExpensesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API expenses ID params
func (o *DeleteAPIExpensesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIExpensesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
