// Code generated by go-swagger; DO NOT EDIT.

package expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// PatchAPIExpensesIDDuplicateReader is a Reader for the PatchAPIExpensesIDDuplicate structure.
type PatchAPIExpensesIDDuplicateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIExpensesIDDuplicateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIExpensesIDDuplicateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPIExpensesIDDuplicateOK creates a PatchAPIExpensesIDDuplicateOK with default headers values
func NewPatchAPIExpensesIDDuplicateOK() *PatchAPIExpensesIDDuplicateOK {
	return &PatchAPIExpensesIDDuplicateOK{}
}

/*
PatchAPIExpensesIDDuplicateOK describes a response with status code 200, with default header values.

Duplicates a expense record, resetting the export state only.
*/
type PatchAPIExpensesIDDuplicateOK struct {
	Payload *models.ExpenseEntity
}

// IsSuccess returns true when this patch Api expenses Id duplicate o k response has a 2xx status code
func (o *PatchAPIExpensesIDDuplicateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api expenses Id duplicate o k response has a 3xx status code
func (o *PatchAPIExpensesIDDuplicateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api expenses Id duplicate o k response has a 4xx status code
func (o *PatchAPIExpensesIDDuplicateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api expenses Id duplicate o k response has a 5xx status code
func (o *PatchAPIExpensesIDDuplicateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api expenses Id duplicate o k response a status code equal to that given
func (o *PatchAPIExpensesIDDuplicateOK) IsCode(code int) bool {
	return code == 200
}

func (o *PatchAPIExpensesIDDuplicateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/expenses/{id}/duplicate][%d] patchApiExpensesIdDuplicateOK  %+v", 200, o.Payload)
}

func (o *PatchAPIExpensesIDDuplicateOK) String() string {
	return fmt.Sprintf("[PATCH /api/expenses/{id}/duplicate][%d] patchApiExpensesIdDuplicateOK  %+v", 200, o.Payload)
}

func (o *PatchAPIExpensesIDDuplicateOK) GetPayload() *models.ExpenseEntity {
	return o.Payload
}

func (o *PatchAPIExpensesIDDuplicateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpenseEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
