// Code generated by go-swagger; DO NOT EDIT.

package expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// PostAPIExpensesReader is a Reader for the PostAPIExpenses structure.
type PostAPIExpensesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIExpensesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIExpensesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIExpensesOK creates a PostAPIExpensesOK with default headers values
func NewPostAPIExpensesOK() *PostAPIExpensesOK {
	return &PostAPIExpensesOK{}
}

/*
PostAPIExpensesOK describes a response with status code 200, with default header values.

Returns the new created expense
*/
type PostAPIExpensesOK struct {
	Payload *models.ExpenseEntity
}

// IsSuccess returns true when this post Api expenses o k response has a 2xx status code
func (o *PostAPIExpensesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api expenses o k response has a 3xx status code
func (o *PostAPIExpensesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api expenses o k response has a 4xx status code
func (o *PostAPIExpensesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api expenses o k response has a 5xx status code
func (o *PostAPIExpensesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api expenses o k response a status code equal to that given
func (o *PostAPIExpensesOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAPIExpensesOK) Error() string {
	return fmt.Sprintf("[POST /api/expenses][%d] postApiExpensesOK  %+v", 200, o.Payload)
}

func (o *PostAPIExpensesOK) String() string {
	return fmt.Sprintf("[POST /api/expenses][%d] postApiExpensesOK  %+v", 200, o.Payload)
}

func (o *PostAPIExpensesOK) GetPayload() *models.ExpenseEntity {
	return o.Payload
}

func (o *PostAPIExpensesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpenseEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
