// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIUsersMeParams creates a new GetAPIUsersMeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIUsersMeParams() *GetAPIUsersMeParams {
	return &GetAPIUsersMeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIUsersMeParamsWithTimeout creates a new GetAPIUsersMeParams object
// with the ability to set a timeout on a request.
func NewGetAPIUsersMeParamsWithTimeout(timeout time.Duration) *GetAPIUsersMeParams {
	return &GetAPIUsersMeParams{
		timeout: timeout,
	}
}

// NewGetAPIUsersMeParamsWithContext creates a new GetAPIUsersMeParams object
// with the ability to set a context for a request.
func NewGetAPIUsersMeParamsWithContext(ctx context.Context) *GetAPIUsersMeParams {
	return &GetAPIUsersMeParams{
		Context: ctx,
	}
}

// NewGetAPIUsersMeParamsWithHTTPClient creates a new GetAPIUsersMeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIUsersMeParamsWithHTTPClient(client *http.Client) *GetAPIUsersMeParams {
	return &GetAPIUsersMeParams{
		HTTPClient: client,
	}
}

/*
GetAPIUsersMeParams contains all the parameters to send to the API endpoint

	for the get API users me operation.

	Typically these are written to a http.Request.
*/
type GetAPIUsersMeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUsersMeParams) WithDefaults() *GetAPIUsersMeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUsersMeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API users me params
func (o *GetAPIUsersMeParams) WithTimeout(timeout time.Duration) *GetAPIUsersMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API users me params
func (o *GetAPIUsersMeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API users me params
func (o *GetAPIUsersMeParams) WithContext(ctx context.Context) *GetAPIUsersMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API users me params
func (o *GetAPIUsersMeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API users me params
func (o *GetAPIUsersMeParams) WithHTTPClient(client *http.Client) *GetAPIUsersMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API users me params
func (o *GetAPIUsersMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIUsersMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
