// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIUsersIDParams creates a new GetAPIUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIUsersIDParams() *GetAPIUsersIDParams {
	return &GetAPIUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIUsersIDParamsWithTimeout creates a new GetAPIUsersIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIUsersIDParamsWithTimeout(timeout time.Duration) *GetAPIUsersIDParams {
	return &GetAPIUsersIDParams{
		timeout: timeout,
	}
}

// NewGetAPIUsersIDParamsWithContext creates a new GetAPIUsersIDParams object
// with the ability to set a context for a request.
func NewGetAPIUsersIDParamsWithContext(ctx context.Context) *GetAPIUsersIDParams {
	return &GetAPIUsersIDParams{
		Context: ctx,
	}
}

// NewGetAPIUsersIDParamsWithHTTPClient creates a new GetAPIUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIUsersIDParamsWithHTTPClient(client *http.Client) *GetAPIUsersIDParams {
	return &GetAPIUsersIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIUsersIDParams contains all the parameters to send to the API endpoint

	for the get API users ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIUsersIDParams struct {

	/* ID.

	   User ID to fetch
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUsersIDParams) WithDefaults() *GetAPIUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API users ID params
func (o *GetAPIUsersIDParams) WithTimeout(timeout time.Duration) *GetAPIUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API users ID params
func (o *GetAPIUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API users ID params
func (o *GetAPIUsersIDParams) WithContext(ctx context.Context) *GetAPIUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API users ID params
func (o *GetAPIUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API users ID params
func (o *GetAPIUsersIDParams) WithHTTPClient(client *http.Client) *GetAPIUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API users ID params
func (o *GetAPIUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API users ID params
func (o *GetAPIUsersIDParams) WithID(id int64) *GetAPIUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API users ID params
func (o *GetAPIUsersIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
