// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/decentral1se/go-kimai/models"
)

// NewPatchAPIUsersIDParams creates a new PatchAPIUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIUsersIDParams() *PatchAPIUsersIDParams {
	return &PatchAPIUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIUsersIDParamsWithTimeout creates a new PatchAPIUsersIDParams object
// with the ability to set a timeout on a request.
func NewPatchAPIUsersIDParamsWithTimeout(timeout time.Duration) *PatchAPIUsersIDParams {
	return &PatchAPIUsersIDParams{
		timeout: timeout,
	}
}

// NewPatchAPIUsersIDParamsWithContext creates a new PatchAPIUsersIDParams object
// with the ability to set a context for a request.
func NewPatchAPIUsersIDParamsWithContext(ctx context.Context) *PatchAPIUsersIDParams {
	return &PatchAPIUsersIDParams{
		Context: ctx,
	}
}

// NewPatchAPIUsersIDParamsWithHTTPClient creates a new PatchAPIUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIUsersIDParamsWithHTTPClient(client *http.Client) *PatchAPIUsersIDParams {
	return &PatchAPIUsersIDParams{
		HTTPClient: client,
	}
}

/*
PatchAPIUsersIDParams contains all the parameters to send to the API endpoint

	for the patch API users ID operation.

	Typically these are written to a http.Request.
*/
type PatchAPIUsersIDParams struct {

	// Body.
	Body *models.UserEditForm

	/* ID.

	   User ID to update
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIUsersIDParams) WithDefaults() *PatchAPIUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API users ID params
func (o *PatchAPIUsersIDParams) WithTimeout(timeout time.Duration) *PatchAPIUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API users ID params
func (o *PatchAPIUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API users ID params
func (o *PatchAPIUsersIDParams) WithContext(ctx context.Context) *PatchAPIUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API users ID params
func (o *PatchAPIUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API users ID params
func (o *PatchAPIUsersIDParams) WithHTTPClient(client *http.Client) *PatchAPIUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API users ID params
func (o *PatchAPIUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API users ID params
func (o *PatchAPIUsersIDParams) WithBody(body *models.UserEditForm) *PatchAPIUsersIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API users ID params
func (o *PatchAPIUsersIDParams) SetBody(body *models.UserEditForm) {
	o.Body = body
}

// WithID adds the id to the patch API users ID params
func (o *PatchAPIUsersIDParams) WithID(id int64) *PatchAPIUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API users ID params
func (o *PatchAPIUsersIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
