// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPITasksIDReader is a Reader for the DeleteAPITasksID structure.
type DeleteAPITasksIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPITasksIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPITasksIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPITasksIDNoContent creates a DeleteAPITasksIDNoContent with default headers values
func NewDeleteAPITasksIDNoContent() *DeleteAPITasksIDNoContent {
	return &DeleteAPITasksIDNoContent{}
}

/*
DeleteAPITasksIDNoContent describes a response with status code 204, with default header values.

Delete one task record
*/
type DeleteAPITasksIDNoContent struct {
}

// IsSuccess returns true when this delete Api tasks Id no content response has a 2xx status code
func (o *DeleteAPITasksIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api tasks Id no content response has a 3xx status code
func (o *DeleteAPITasksIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api tasks Id no content response has a 4xx status code
func (o *DeleteAPITasksIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api tasks Id no content response has a 5xx status code
func (o *DeleteAPITasksIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api tasks Id no content response a status code equal to that given
func (o *DeleteAPITasksIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteAPITasksIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/tasks/{id}][%d] deleteApiTasksIdNoContent ", 204)
}

func (o *DeleteAPITasksIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/tasks/{id}][%d] deleteApiTasksIdNoContent ", 204)
}

func (o *DeleteAPITasksIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
