// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPITasksIDParams creates a new DeleteAPITasksIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPITasksIDParams() *DeleteAPITasksIDParams {
	return &DeleteAPITasksIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPITasksIDParamsWithTimeout creates a new DeleteAPITasksIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPITasksIDParamsWithTimeout(timeout time.Duration) *DeleteAPITasksIDParams {
	return &DeleteAPITasksIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPITasksIDParamsWithContext creates a new DeleteAPITasksIDParams object
// with the ability to set a context for a request.
func NewDeleteAPITasksIDParamsWithContext(ctx context.Context) *DeleteAPITasksIDParams {
	return &DeleteAPITasksIDParams{
		Context: ctx,
	}
}

// NewDeleteAPITasksIDParamsWithHTTPClient creates a new DeleteAPITasksIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPITasksIDParamsWithHTTPClient(client *http.Client) *DeleteAPITasksIDParams {
	return &DeleteAPITasksIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPITasksIDParams contains all the parameters to send to the API endpoint

	for the delete API tasks ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPITasksIDParams struct {

	/* ID.

	   Task record ID to delete
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API tasks ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITasksIDParams) WithDefaults() *DeleteAPITasksIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API tasks ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITasksIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) WithTimeout(timeout time.Duration) *DeleteAPITasksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) WithContext(ctx context.Context) *DeleteAPITasksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) WithHTTPClient(client *http.Client) *DeleteAPITasksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) WithID(id int64) *DeleteAPITasksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API tasks ID params
func (o *DeleteAPITasksIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPITasksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
