// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// GetAPITasksIDReader is a Reader for the GetAPITasksID structure.
type GetAPITasksIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPITasksIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPITasksIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPITasksIDOK creates a GetAPITasksIDOK with default headers values
func NewGetAPITasksIDOK() *GetAPITasksIDOK {
	return &GetAPITasksIDOK{}
}

/*
GetAPITasksIDOK describes a response with status code 200, with default header values.

Returns one task entity
*/
type GetAPITasksIDOK struct {
	Payload *models.Task
}

// IsSuccess returns true when this get Api tasks Id o k response has a 2xx status code
func (o *GetAPITasksIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api tasks Id o k response has a 3xx status code
func (o *GetAPITasksIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api tasks Id o k response has a 4xx status code
func (o *GetAPITasksIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api tasks Id o k response has a 5xx status code
func (o *GetAPITasksIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api tasks Id o k response a status code equal to that given
func (o *GetAPITasksIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPITasksIDOK) Error() string {
	return fmt.Sprintf("[GET /api/tasks/{id}][%d] getApiTasksIdOK  %+v", 200, o.Payload)
}

func (o *GetAPITasksIDOK) String() string {
	return fmt.Sprintf("[GET /api/tasks/{id}][%d] getApiTasksIdOK  %+v", 200, o.Payload)
}

func (o *GetAPITasksIDOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *GetAPITasksIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
