// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchAPITasksIDCloseParams creates a new PatchAPITasksIDCloseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPITasksIDCloseParams() *PatchAPITasksIDCloseParams {
	return &PatchAPITasksIDCloseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPITasksIDCloseParamsWithTimeout creates a new PatchAPITasksIDCloseParams object
// with the ability to set a timeout on a request.
func NewPatchAPITasksIDCloseParamsWithTimeout(timeout time.Duration) *PatchAPITasksIDCloseParams {
	return &PatchAPITasksIDCloseParams{
		timeout: timeout,
	}
}

// NewPatchAPITasksIDCloseParamsWithContext creates a new PatchAPITasksIDCloseParams object
// with the ability to set a context for a request.
func NewPatchAPITasksIDCloseParamsWithContext(ctx context.Context) *PatchAPITasksIDCloseParams {
	return &PatchAPITasksIDCloseParams{
		Context: ctx,
	}
}

// NewPatchAPITasksIDCloseParamsWithHTTPClient creates a new PatchAPITasksIDCloseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPITasksIDCloseParamsWithHTTPClient(client *http.Client) *PatchAPITasksIDCloseParams {
	return &PatchAPITasksIDCloseParams{
		HTTPClient: client,
	}
}

/*
PatchAPITasksIDCloseParams contains all the parameters to send to the API endpoint

	for the patch API tasks ID close operation.

	Typically these are written to a http.Request.
*/
type PatchAPITasksIDCloseParams struct {

	/* ID.

	   Task ID to close
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API tasks ID close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITasksIDCloseParams) WithDefaults() *PatchAPITasksIDCloseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API tasks ID close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITasksIDCloseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) WithTimeout(timeout time.Duration) *PatchAPITasksIDCloseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) WithContext(ctx context.Context) *PatchAPITasksIDCloseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) WithHTTPClient(client *http.Client) *PatchAPITasksIDCloseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) WithID(id int64) *PatchAPITasksIDCloseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API tasks ID close params
func (o *PatchAPITasksIDCloseParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPITasksIDCloseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
