// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchAPITasksIDStopParams creates a new PatchAPITasksIDStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPITasksIDStopParams() *PatchAPITasksIDStopParams {
	return &PatchAPITasksIDStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPITasksIDStopParamsWithTimeout creates a new PatchAPITasksIDStopParams object
// with the ability to set a timeout on a request.
func NewPatchAPITasksIDStopParamsWithTimeout(timeout time.Duration) *PatchAPITasksIDStopParams {
	return &PatchAPITasksIDStopParams{
		timeout: timeout,
	}
}

// NewPatchAPITasksIDStopParamsWithContext creates a new PatchAPITasksIDStopParams object
// with the ability to set a context for a request.
func NewPatchAPITasksIDStopParamsWithContext(ctx context.Context) *PatchAPITasksIDStopParams {
	return &PatchAPITasksIDStopParams{
		Context: ctx,
	}
}

// NewPatchAPITasksIDStopParamsWithHTTPClient creates a new PatchAPITasksIDStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPITasksIDStopParamsWithHTTPClient(client *http.Client) *PatchAPITasksIDStopParams {
	return &PatchAPITasksIDStopParams{
		HTTPClient: client,
	}
}

/*
PatchAPITasksIDStopParams contains all the parameters to send to the API endpoint

	for the patch API tasks ID stop operation.

	Typically these are written to a http.Request.
*/
type PatchAPITasksIDStopParams struct {

	/* ID.

	   Task ID to stop
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API tasks ID stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITasksIDStopParams) WithDefaults() *PatchAPITasksIDStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API tasks ID stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITasksIDStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) WithTimeout(timeout time.Duration) *PatchAPITasksIDStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) WithContext(ctx context.Context) *PatchAPITasksIDStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) WithHTTPClient(client *http.Client) *PatchAPITasksIDStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) WithID(id int64) *PatchAPITasksIDStopParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API tasks ID stop params
func (o *PatchAPITasksIDStopParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPITasksIDStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
