// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// PatchAPITasksIDLogReader is a Reader for the PatchAPITasksIDLog structure.
type PatchAPITasksIDLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPITasksIDLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPITasksIDLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPITasksIDLogOK creates a PatchAPITasksIDLogOK with default headers values
func NewPatchAPITasksIDLogOK() *PatchAPITasksIDLogOK {
	return &PatchAPITasksIDLogOK{}
}

/*
PatchAPITasksIDLogOK describes a response with status code 200, with default header values.

Logs already performed work on a task
*/
type PatchAPITasksIDLogOK struct {
	Payload *models.TimesheetEntityExpanded
}

// IsSuccess returns true when this patch Api tasks Id log o k response has a 2xx status code
func (o *PatchAPITasksIDLogOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api tasks Id log o k response has a 3xx status code
func (o *PatchAPITasksIDLogOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api tasks Id log o k response has a 4xx status code
func (o *PatchAPITasksIDLogOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api tasks Id log o k response has a 5xx status code
func (o *PatchAPITasksIDLogOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api tasks Id log o k response a status code equal to that given
func (o *PatchAPITasksIDLogOK) IsCode(code int) bool {
	return code == 200
}

func (o *PatchAPITasksIDLogOK) Error() string {
	return fmt.Sprintf("[PATCH /api/tasks/{id}/log][%d] patchApiTasksIdLogOK  %+v", 200, o.Payload)
}

func (o *PatchAPITasksIDLogOK) String() string {
	return fmt.Sprintf("[PATCH /api/tasks/{id}/log][%d] patchApiTasksIdLogOK  %+v", 200, o.Payload)
}

func (o *PatchAPITasksIDLogOK) GetPayload() *models.TimesheetEntityExpanded {
	return o.Payload
}

func (o *PatchAPITasksIDLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimesheetEntityExpanded)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
