// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// PatchAPITasksIDReopenReader is a Reader for the PatchAPITasksIDReopen structure.
type PatchAPITasksIDReopenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPITasksIDReopenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPITasksIDReopenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPITasksIDReopenOK creates a PatchAPITasksIDReopenOK with default headers values
func NewPatchAPITasksIDReopenOK() *PatchAPITasksIDReopenOK {
	return &PatchAPITasksIDReopenOK{}
}

/*
PatchAPITasksIDReopenOK describes a response with status code 200, with default header values.

Returns the reopened task
*/
type PatchAPITasksIDReopenOK struct {
	Payload *models.Task
}

// IsSuccess returns true when this patch Api tasks Id reopen o k response has a 2xx status code
func (o *PatchAPITasksIDReopenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api tasks Id reopen o k response has a 3xx status code
func (o *PatchAPITasksIDReopenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api tasks Id reopen o k response has a 4xx status code
func (o *PatchAPITasksIDReopenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api tasks Id reopen o k response has a 5xx status code
func (o *PatchAPITasksIDReopenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api tasks Id reopen o k response a status code equal to that given
func (o *PatchAPITasksIDReopenOK) IsCode(code int) bool {
	return code == 200
}

func (o *PatchAPITasksIDReopenOK) Error() string {
	return fmt.Sprintf("[PATCH /api/tasks/{id}/reopen][%d] patchApiTasksIdReopenOK  %+v", 200, o.Payload)
}

func (o *PatchAPITasksIDReopenOK) String() string {
	return fmt.Sprintf("[PATCH /api/tasks/{id}/reopen][%d] patchApiTasksIdReopenOK  %+v", 200, o.Payload)
}

func (o *PatchAPITasksIDReopenOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *PatchAPITasksIDReopenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
