// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// PostAPITasksReader is a Reader for the PostAPITasks structure.
type PostAPITasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPITasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPITasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPITasksOK creates a PostAPITasksOK with default headers values
func NewPostAPITasksOK() *PostAPITasksOK {
	return &PostAPITasksOK{}
}

/*
PostAPITasksOK describes a response with status code 200, with default header values.

Returns the new created task
*/
type PostAPITasksOK struct {
	Payload *models.Task
}

// IsSuccess returns true when this post Api tasks o k response has a 2xx status code
func (o *PostAPITasksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api tasks o k response has a 3xx status code
func (o *PostAPITasksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api tasks o k response has a 4xx status code
func (o *PostAPITasksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api tasks o k response has a 5xx status code
func (o *PostAPITasksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api tasks o k response a status code equal to that given
func (o *PostAPITasksOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAPITasksOK) Error() string {
	return fmt.Sprintf("[POST /api/tasks][%d] postApiTasksOK  %+v", 200, o.Payload)
}

func (o *PostAPITasksOK) String() string {
	return fmt.Sprintf("[POST /api/tasks][%d] postApiTasksOK  %+v", 200, o.Payload)
}

func (o *PostAPITasksOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *PostAPITasksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
