// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPIActivitiesIDRatesRateIDParams creates a new DeleteAPIActivitiesIDRatesRateIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIActivitiesIDRatesRateIDParams() *DeleteAPIActivitiesIDRatesRateIDParams {
	return &DeleteAPIActivitiesIDRatesRateIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIActivitiesIDRatesRateIDParamsWithTimeout creates a new DeleteAPIActivitiesIDRatesRateIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIActivitiesIDRatesRateIDParamsWithTimeout(timeout time.Duration) *DeleteAPIActivitiesIDRatesRateIDParams {
	return &DeleteAPIActivitiesIDRatesRateIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIActivitiesIDRatesRateIDParamsWithContext creates a new DeleteAPIActivitiesIDRatesRateIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIActivitiesIDRatesRateIDParamsWithContext(ctx context.Context) *DeleteAPIActivitiesIDRatesRateIDParams {
	return &DeleteAPIActivitiesIDRatesRateIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIActivitiesIDRatesRateIDParamsWithHTTPClient creates a new DeleteAPIActivitiesIDRatesRateIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIActivitiesIDRatesRateIDParamsWithHTTPClient(client *http.Client) *DeleteAPIActivitiesIDRatesRateIDParams {
	return &DeleteAPIActivitiesIDRatesRateIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIActivitiesIDRatesRateIDParams contains all the parameters to send to the API endpoint

	for the delete API activities ID rates rate ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIActivitiesIDRatesRateIDParams struct {

	/* ID.

	   The activity whose rate will be removed
	*/
	ID int64

	/* RateID.

	   The rate to remove
	*/
	RateID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API activities ID rates rate ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithDefaults() *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API activities ID rates rate ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithTimeout(timeout time.Duration) *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithContext(ctx context.Context) *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithHTTPClient(client *http.Client) *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithID(id int64) *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetID(id int64) {
	o.ID = id
}

// WithRateID adds the rateID to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WithRateID(rateID int64) *DeleteAPIActivitiesIDRatesRateIDParams {
	o.SetRateID(rateID)
	return o
}

// SetRateID adds the rateId to the delete API activities ID rates rate ID params
func (o *DeleteAPIActivitiesIDRatesRateIDParams) SetRateID(rateID int64) {
	o.RateID = rateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIActivitiesIDRatesRateIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param rateId
	if err := r.SetPathParam("rateId", swag.FormatInt64(o.RateID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
