// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// GetAPIActivitiesIDReader is a Reader for the GetAPIActivitiesID structure.
type GetAPIActivitiesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIActivitiesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIActivitiesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIActivitiesIDOK creates a GetAPIActivitiesIDOK with default headers values
func NewGetAPIActivitiesIDOK() *GetAPIActivitiesIDOK {
	return &GetAPIActivitiesIDOK{}
}

/*
GetAPIActivitiesIDOK describes a response with status code 200, with default header values.

Returns one activity entity
*/
type GetAPIActivitiesIDOK struct {
	Payload *models.ActivityEntity
}

// IsSuccess returns true when this get Api activities Id o k response has a 2xx status code
func (o *GetAPIActivitiesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api activities Id o k response has a 3xx status code
func (o *GetAPIActivitiesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api activities Id o k response has a 4xx status code
func (o *GetAPIActivitiesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api activities Id o k response has a 5xx status code
func (o *GetAPIActivitiesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api activities Id o k response a status code equal to that given
func (o *GetAPIActivitiesIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPIActivitiesIDOK) Error() string {
	return fmt.Sprintf("[GET /api/activities/{id}][%d] getApiActivitiesIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIActivitiesIDOK) String() string {
	return fmt.Sprintf("[GET /api/activities/{id}][%d] getApiActivitiesIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIActivitiesIDOK) GetPayload() *models.ActivityEntity {
	return o.Payload
}

func (o *GetAPIActivitiesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
