// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// GetAPIActivitiesIDRatesReader is a Reader for the GetAPIActivitiesIDRates structure.
type GetAPIActivitiesIDRatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIActivitiesIDRatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIActivitiesIDRatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIActivitiesIDRatesOK creates a GetAPIActivitiesIDRatesOK with default headers values
func NewGetAPIActivitiesIDRatesOK() *GetAPIActivitiesIDRatesOK {
	return &GetAPIActivitiesIDRatesOK{}
}

/*
GetAPIActivitiesIDRatesOK describes a response with status code 200, with default header values.

Returns a collection of activity rate entities
*/
type GetAPIActivitiesIDRatesOK struct {
	Payload []*models.ActivityRate
}

// IsSuccess returns true when this get Api activities Id rates o k response has a 2xx status code
func (o *GetAPIActivitiesIDRatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api activities Id rates o k response has a 3xx status code
func (o *GetAPIActivitiesIDRatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api activities Id rates o k response has a 4xx status code
func (o *GetAPIActivitiesIDRatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api activities Id rates o k response has a 5xx status code
func (o *GetAPIActivitiesIDRatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api activities Id rates o k response a status code equal to that given
func (o *GetAPIActivitiesIDRatesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPIActivitiesIDRatesOK) Error() string {
	return fmt.Sprintf("[GET /api/activities/{id}/rates][%d] getApiActivitiesIdRatesOK  %+v", 200, o.Payload)
}

func (o *GetAPIActivitiesIDRatesOK) String() string {
	return fmt.Sprintf("[GET /api/activities/{id}/rates][%d] getApiActivitiesIdRatesOK  %+v", 200, o.Payload)
}

func (o *GetAPIActivitiesIDRatesOK) GetPayload() []*models.ActivityRate {
	return o.Payload
}

func (o *GetAPIActivitiesIDRatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
