// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIActivitiesIDRatesParams creates a new GetAPIActivitiesIDRatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIActivitiesIDRatesParams() *GetAPIActivitiesIDRatesParams {
	return &GetAPIActivitiesIDRatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIActivitiesIDRatesParamsWithTimeout creates a new GetAPIActivitiesIDRatesParams object
// with the ability to set a timeout on a request.
func NewGetAPIActivitiesIDRatesParamsWithTimeout(timeout time.Duration) *GetAPIActivitiesIDRatesParams {
	return &GetAPIActivitiesIDRatesParams{
		timeout: timeout,
	}
}

// NewGetAPIActivitiesIDRatesParamsWithContext creates a new GetAPIActivitiesIDRatesParams object
// with the ability to set a context for a request.
func NewGetAPIActivitiesIDRatesParamsWithContext(ctx context.Context) *GetAPIActivitiesIDRatesParams {
	return &GetAPIActivitiesIDRatesParams{
		Context: ctx,
	}
}

// NewGetAPIActivitiesIDRatesParamsWithHTTPClient creates a new GetAPIActivitiesIDRatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIActivitiesIDRatesParamsWithHTTPClient(client *http.Client) *GetAPIActivitiesIDRatesParams {
	return &GetAPIActivitiesIDRatesParams{
		HTTPClient: client,
	}
}

/*
GetAPIActivitiesIDRatesParams contains all the parameters to send to the API endpoint

	for the get API activities ID rates operation.

	Typically these are written to a http.Request.
*/
type GetAPIActivitiesIDRatesParams struct {

	/* ID.

	   The activity whose rates will be returned
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API activities ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIActivitiesIDRatesParams) WithDefaults() *GetAPIActivitiesIDRatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API activities ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIActivitiesIDRatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) WithTimeout(timeout time.Duration) *GetAPIActivitiesIDRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) WithContext(ctx context.Context) *GetAPIActivitiesIDRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) WithHTTPClient(client *http.Client) *GetAPIActivitiesIDRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) WithID(id int64) *GetAPIActivitiesIDRatesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API activities ID rates params
func (o *GetAPIActivitiesIDRatesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIActivitiesIDRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
