// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// PatchAPIActivitiesIDReader is a Reader for the PatchAPIActivitiesID structure.
type PatchAPIActivitiesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIActivitiesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIActivitiesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPIActivitiesIDOK creates a PatchAPIActivitiesIDOK with default headers values
func NewPatchAPIActivitiesIDOK() *PatchAPIActivitiesIDOK {
	return &PatchAPIActivitiesIDOK{}
}

/*
PatchAPIActivitiesIDOK describes a response with status code 200, with default header values.

Returns the updated activity
*/
type PatchAPIActivitiesIDOK struct {
	Payload *models.ActivityEntity
}

// IsSuccess returns true when this patch Api activities Id o k response has a 2xx status code
func (o *PatchAPIActivitiesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api activities Id o k response has a 3xx status code
func (o *PatchAPIActivitiesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api activities Id o k response has a 4xx status code
func (o *PatchAPIActivitiesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api activities Id o k response has a 5xx status code
func (o *PatchAPIActivitiesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api activities Id o k response a status code equal to that given
func (o *PatchAPIActivitiesIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *PatchAPIActivitiesIDOK) Error() string {
	return fmt.Sprintf("[PATCH /api/activities/{id}][%d] patchApiActivitiesIdOK  %+v", 200, o.Payload)
}

func (o *PatchAPIActivitiesIDOK) String() string {
	return fmt.Sprintf("[PATCH /api/activities/{id}][%d] patchApiActivitiesIdOK  %+v", 200, o.Payload)
}

func (o *PatchAPIActivitiesIDOK) GetPayload() *models.ActivityEntity {
	return o.Payload
}

func (o *PatchAPIActivitiesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
