// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// NewPostAPIActivitiesParams creates a new PostAPIActivitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIActivitiesParams() *PostAPIActivitiesParams {
	return &PostAPIActivitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIActivitiesParamsWithTimeout creates a new PostAPIActivitiesParams object
// with the ability to set a timeout on a request.
func NewPostAPIActivitiesParamsWithTimeout(timeout time.Duration) *PostAPIActivitiesParams {
	return &PostAPIActivitiesParams{
		timeout: timeout,
	}
}

// NewPostAPIActivitiesParamsWithContext creates a new PostAPIActivitiesParams object
// with the ability to set a context for a request.
func NewPostAPIActivitiesParamsWithContext(ctx context.Context) *PostAPIActivitiesParams {
	return &PostAPIActivitiesParams{
		Context: ctx,
	}
}

// NewPostAPIActivitiesParamsWithHTTPClient creates a new PostAPIActivitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIActivitiesParamsWithHTTPClient(client *http.Client) *PostAPIActivitiesParams {
	return &PostAPIActivitiesParams{
		HTTPClient: client,
	}
}

/*
PostAPIActivitiesParams contains all the parameters to send to the API endpoint

	for the post API activities operation.

	Typically these are written to a http.Request.
*/
type PostAPIActivitiesParams struct {

	// Body.
	Body *models.ActivityEditForm

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API activities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIActivitiesParams) WithDefaults() *PostAPIActivitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API activities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIActivitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API activities params
func (o *PostAPIActivitiesParams) WithTimeout(timeout time.Duration) *PostAPIActivitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API activities params
func (o *PostAPIActivitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API activities params
func (o *PostAPIActivitiesParams) WithContext(ctx context.Context) *PostAPIActivitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API activities params
func (o *PostAPIActivitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API activities params
func (o *PostAPIActivitiesParams) WithHTTPClient(client *http.Client) *PostAPIActivitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API activities params
func (o *PostAPIActivitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API activities params
func (o *PostAPIActivitiesParams) WithBody(body *models.ActivityEditForm) *PostAPIActivitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API activities params
func (o *PostAPIActivitiesParams) SetBody(body *models.ActivityEditForm) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIActivitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
