// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/decentral1se/go-kimai/models"
)

// NewPostAPIActivitiesIDRatesParams creates a new PostAPIActivitiesIDRatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIActivitiesIDRatesParams() *PostAPIActivitiesIDRatesParams {
	return &PostAPIActivitiesIDRatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIActivitiesIDRatesParamsWithTimeout creates a new PostAPIActivitiesIDRatesParams object
// with the ability to set a timeout on a request.
func NewPostAPIActivitiesIDRatesParamsWithTimeout(timeout time.Duration) *PostAPIActivitiesIDRatesParams {
	return &PostAPIActivitiesIDRatesParams{
		timeout: timeout,
	}
}

// NewPostAPIActivitiesIDRatesParamsWithContext creates a new PostAPIActivitiesIDRatesParams object
// with the ability to set a context for a request.
func NewPostAPIActivitiesIDRatesParamsWithContext(ctx context.Context) *PostAPIActivitiesIDRatesParams {
	return &PostAPIActivitiesIDRatesParams{
		Context: ctx,
	}
}

// NewPostAPIActivitiesIDRatesParamsWithHTTPClient creates a new PostAPIActivitiesIDRatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIActivitiesIDRatesParamsWithHTTPClient(client *http.Client) *PostAPIActivitiesIDRatesParams {
	return &PostAPIActivitiesIDRatesParams{
		HTTPClient: client,
	}
}

/*
PostAPIActivitiesIDRatesParams contains all the parameters to send to the API endpoint

	for the post API activities ID rates operation.

	Typically these are written to a http.Request.
*/
type PostAPIActivitiesIDRatesParams struct {

	// Body.
	Body *models.ActivityRateForm

	/* ID.

	   The activity to add the rate for
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API activities ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIActivitiesIDRatesParams) WithDefaults() *PostAPIActivitiesIDRatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API activities ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIActivitiesIDRatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) WithTimeout(timeout time.Duration) *PostAPIActivitiesIDRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) WithContext(ctx context.Context) *PostAPIActivitiesIDRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) WithHTTPClient(client *http.Client) *PostAPIActivitiesIDRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) WithBody(body *models.ActivityRateForm) *PostAPIActivitiesIDRatesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) SetBody(body *models.ActivityRateForm) {
	o.Body = body
}

// WithID adds the id to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) WithID(id int64) *PostAPIActivitiesIDRatesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post API activities ID rates params
func (o *PostAPIActivitiesIDRatesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIActivitiesIDRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
