// Code generated by go-swagger; DO NOT EDIT.

package timesheet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPITimesheetsIDParams creates a new DeleteAPITimesheetsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPITimesheetsIDParams() *DeleteAPITimesheetsIDParams {
	return &DeleteAPITimesheetsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPITimesheetsIDParamsWithTimeout creates a new DeleteAPITimesheetsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPITimesheetsIDParamsWithTimeout(timeout time.Duration) *DeleteAPITimesheetsIDParams {
	return &DeleteAPITimesheetsIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPITimesheetsIDParamsWithContext creates a new DeleteAPITimesheetsIDParams object
// with the ability to set a context for a request.
func NewDeleteAPITimesheetsIDParamsWithContext(ctx context.Context) *DeleteAPITimesheetsIDParams {
	return &DeleteAPITimesheetsIDParams{
		Context: ctx,
	}
}

// NewDeleteAPITimesheetsIDParamsWithHTTPClient creates a new DeleteAPITimesheetsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPITimesheetsIDParamsWithHTTPClient(client *http.Client) *DeleteAPITimesheetsIDParams {
	return &DeleteAPITimesheetsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPITimesheetsIDParams contains all the parameters to send to the API endpoint

	for the delete API timesheets ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPITimesheetsIDParams struct {

	/* ID.

	   Timesheet record ID to delete
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API timesheets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITimesheetsIDParams) WithDefaults() *DeleteAPITimesheetsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API timesheets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITimesheetsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) WithTimeout(timeout time.Duration) *DeleteAPITimesheetsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) WithContext(ctx context.Context) *DeleteAPITimesheetsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) WithHTTPClient(client *http.Client) *DeleteAPITimesheetsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) WithID(id int64) *DeleteAPITimesheetsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API timesheets ID params
func (o *DeleteAPITimesheetsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPITimesheetsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
