// Code generated by go-swagger; DO NOT EDIT.

package timesheet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// GetAPITimesheetsIDReader is a Reader for the GetAPITimesheetsID structure.
type GetAPITimesheetsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPITimesheetsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPITimesheetsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPITimesheetsIDOK creates a GetAPITimesheetsIDOK with default headers values
func NewGetAPITimesheetsIDOK() *GetAPITimesheetsIDOK {
	return &GetAPITimesheetsIDOK{}
}

/*
GetAPITimesheetsIDOK describes a response with status code 200, with default header values.

Returns one timesheet record. Be aware that the datetime fields are given in the users local time including the timezone offset via ISO 8601.
*/
type GetAPITimesheetsIDOK struct {
	Payload *models.TimesheetEntity
}

// IsSuccess returns true when this get Api timesheets Id o k response has a 2xx status code
func (o *GetAPITimesheetsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api timesheets Id o k response has a 3xx status code
func (o *GetAPITimesheetsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api timesheets Id o k response has a 4xx status code
func (o *GetAPITimesheetsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api timesheets Id o k response has a 5xx status code
func (o *GetAPITimesheetsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api timesheets Id o k response a status code equal to that given
func (o *GetAPITimesheetsIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPITimesheetsIDOK) Error() string {
	return fmt.Sprintf("[GET /api/timesheets/{id}][%d] getApiTimesheetsIdOK  %+v", 200, o.Payload)
}

func (o *GetAPITimesheetsIDOK) String() string {
	return fmt.Sprintf("[GET /api/timesheets/{id}][%d] getApiTimesheetsIdOK  %+v", 200, o.Payload)
}

func (o *GetAPITimesheetsIDOK) GetPayload() *models.TimesheetEntity {
	return o.Payload
}

func (o *GetAPITimesheetsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimesheetEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
