// Code generated by go-swagger; DO NOT EDIT.

package timesheet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPITimesheetsIDParams creates a new GetAPITimesheetsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPITimesheetsIDParams() *GetAPITimesheetsIDParams {
	return &GetAPITimesheetsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPITimesheetsIDParamsWithTimeout creates a new GetAPITimesheetsIDParams object
// with the ability to set a timeout on a request.
func NewGetAPITimesheetsIDParamsWithTimeout(timeout time.Duration) *GetAPITimesheetsIDParams {
	return &GetAPITimesheetsIDParams{
		timeout: timeout,
	}
}

// NewGetAPITimesheetsIDParamsWithContext creates a new GetAPITimesheetsIDParams object
// with the ability to set a context for a request.
func NewGetAPITimesheetsIDParamsWithContext(ctx context.Context) *GetAPITimesheetsIDParams {
	return &GetAPITimesheetsIDParams{
		Context: ctx,
	}
}

// NewGetAPITimesheetsIDParamsWithHTTPClient creates a new GetAPITimesheetsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPITimesheetsIDParamsWithHTTPClient(client *http.Client) *GetAPITimesheetsIDParams {
	return &GetAPITimesheetsIDParams{
		HTTPClient: client,
	}
}

/*
GetAPITimesheetsIDParams contains all the parameters to send to the API endpoint

	for the get API timesheets ID operation.

	Typically these are written to a http.Request.
*/
type GetAPITimesheetsIDParams struct {

	/* ID.

	   Timesheet record ID to fetch
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API timesheets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITimesheetsIDParams) WithDefaults() *GetAPITimesheetsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API timesheets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITimesheetsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) WithTimeout(timeout time.Duration) *GetAPITimesheetsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) WithContext(ctx context.Context) *GetAPITimesheetsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) WithHTTPClient(client *http.Client) *GetAPITimesheetsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) WithID(id int64) *GetAPITimesheetsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API timesheets ID params
func (o *GetAPITimesheetsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPITimesheetsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
