// Code generated by go-swagger; DO NOT EDIT.

package timesheet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchAPITimesheetsIDMetaParams creates a new PatchAPITimesheetsIDMetaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPITimesheetsIDMetaParams() *PatchAPITimesheetsIDMetaParams {
	return &PatchAPITimesheetsIDMetaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPITimesheetsIDMetaParamsWithTimeout creates a new PatchAPITimesheetsIDMetaParams object
// with the ability to set a timeout on a request.
func NewPatchAPITimesheetsIDMetaParamsWithTimeout(timeout time.Duration) *PatchAPITimesheetsIDMetaParams {
	return &PatchAPITimesheetsIDMetaParams{
		timeout: timeout,
	}
}

// NewPatchAPITimesheetsIDMetaParamsWithContext creates a new PatchAPITimesheetsIDMetaParams object
// with the ability to set a context for a request.
func NewPatchAPITimesheetsIDMetaParamsWithContext(ctx context.Context) *PatchAPITimesheetsIDMetaParams {
	return &PatchAPITimesheetsIDMetaParams{
		Context: ctx,
	}
}

// NewPatchAPITimesheetsIDMetaParamsWithHTTPClient creates a new PatchAPITimesheetsIDMetaParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPITimesheetsIDMetaParamsWithHTTPClient(client *http.Client) *PatchAPITimesheetsIDMetaParams {
	return &PatchAPITimesheetsIDMetaParams{
		HTTPClient: client,
	}
}

/*
PatchAPITimesheetsIDMetaParams contains all the parameters to send to the API endpoint

	for the patch API timesheets ID meta operation.

	Typically these are written to a http.Request.
*/
type PatchAPITimesheetsIDMetaParams struct {

	// Body.
	Body PatchAPITimesheetsIDMetaBody

	/* ID.

	   Timesheet record ID to set the meta-field value for
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API timesheets ID meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITimesheetsIDMetaParams) WithDefaults() *PatchAPITimesheetsIDMetaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API timesheets ID meta params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITimesheetsIDMetaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) WithTimeout(timeout time.Duration) *PatchAPITimesheetsIDMetaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) WithContext(ctx context.Context) *PatchAPITimesheetsIDMetaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) WithHTTPClient(client *http.Client) *PatchAPITimesheetsIDMetaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) WithBody(body PatchAPITimesheetsIDMetaBody) *PatchAPITimesheetsIDMetaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) SetBody(body PatchAPITimesheetsIDMetaBody) {
	o.Body = body
}

// WithID adds the id to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) WithID(id int64) *PatchAPITimesheetsIDMetaParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API timesheets ID meta params
func (o *PatchAPITimesheetsIDMetaParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPITimesheetsIDMetaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
