// Code generated by go-swagger; DO NOT EDIT.

package timesheet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchAPITimesheetsIDDuplicateParams creates a new PatchAPITimesheetsIDDuplicateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPITimesheetsIDDuplicateParams() *PatchAPITimesheetsIDDuplicateParams {
	return &PatchAPITimesheetsIDDuplicateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPITimesheetsIDDuplicateParamsWithTimeout creates a new PatchAPITimesheetsIDDuplicateParams object
// with the ability to set a timeout on a request.
func NewPatchAPITimesheetsIDDuplicateParamsWithTimeout(timeout time.Duration) *PatchAPITimesheetsIDDuplicateParams {
	return &PatchAPITimesheetsIDDuplicateParams{
		timeout: timeout,
	}
}

// NewPatchAPITimesheetsIDDuplicateParamsWithContext creates a new PatchAPITimesheetsIDDuplicateParams object
// with the ability to set a context for a request.
func NewPatchAPITimesheetsIDDuplicateParamsWithContext(ctx context.Context) *PatchAPITimesheetsIDDuplicateParams {
	return &PatchAPITimesheetsIDDuplicateParams{
		Context: ctx,
	}
}

// NewPatchAPITimesheetsIDDuplicateParamsWithHTTPClient creates a new PatchAPITimesheetsIDDuplicateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPITimesheetsIDDuplicateParamsWithHTTPClient(client *http.Client) *PatchAPITimesheetsIDDuplicateParams {
	return &PatchAPITimesheetsIDDuplicateParams{
		HTTPClient: client,
	}
}

/*
PatchAPITimesheetsIDDuplicateParams contains all the parameters to send to the API endpoint

	for the patch API timesheets ID duplicate operation.

	Typically these are written to a http.Request.
*/
type PatchAPITimesheetsIDDuplicateParams struct {

	/* ID.

	   Timesheet record ID to duplicate
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API timesheets ID duplicate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITimesheetsIDDuplicateParams) WithDefaults() *PatchAPITimesheetsIDDuplicateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API timesheets ID duplicate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITimesheetsIDDuplicateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) WithTimeout(timeout time.Duration) *PatchAPITimesheetsIDDuplicateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) WithContext(ctx context.Context) *PatchAPITimesheetsIDDuplicateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) WithHTTPClient(client *http.Client) *PatchAPITimesheetsIDDuplicateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) WithID(id int64) *PatchAPITimesheetsIDDuplicateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API timesheets ID duplicate params
func (o *PatchAPITimesheetsIDDuplicateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPITimesheetsIDDuplicateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
