// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIProjectsIDRatesRateIDReader is a Reader for the DeleteAPIProjectsIDRatesRateID structure.
type DeleteAPIProjectsIDRatesRateIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIProjectsIDRatesRateIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIProjectsIDRatesRateIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIProjectsIDRatesRateIDNoContent creates a DeleteAPIProjectsIDRatesRateIDNoContent with default headers values
func NewDeleteAPIProjectsIDRatesRateIDNoContent() *DeleteAPIProjectsIDRatesRateIDNoContent {
	return &DeleteAPIProjectsIDRatesRateIDNoContent{}
}

/*
DeleteAPIProjectsIDRatesRateIDNoContent describes a response with status code 204, with default header values.

Returns no content: 204 on successful delete
*/
type DeleteAPIProjectsIDRatesRateIDNoContent struct {
}

// IsSuccess returns true when this delete Api projects Id rates rate Id no content response has a 2xx status code
func (o *DeleteAPIProjectsIDRatesRateIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api projects Id rates rate Id no content response has a 3xx status code
func (o *DeleteAPIProjectsIDRatesRateIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api projects Id rates rate Id no content response has a 4xx status code
func (o *DeleteAPIProjectsIDRatesRateIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api projects Id rates rate Id no content response has a 5xx status code
func (o *DeleteAPIProjectsIDRatesRateIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api projects Id rates rate Id no content response a status code equal to that given
func (o *DeleteAPIProjectsIDRatesRateIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteAPIProjectsIDRatesRateIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/projects/{id}/rates/{rateId}][%d] deleteApiProjectsIdRatesRateIdNoContent ", 204)
}

func (o *DeleteAPIProjectsIDRatesRateIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/projects/{id}/rates/{rateId}][%d] deleteApiProjectsIdRatesRateIdNoContent ", 204)
}

func (o *DeleteAPIProjectsIDRatesRateIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
