// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// GetAPIProjectsReader is a Reader for the GetAPIProjects structure.
type GetAPIProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIProjectsOK creates a GetAPIProjectsOK with default headers values
func NewGetAPIProjectsOK() *GetAPIProjectsOK {
	return &GetAPIProjectsOK{}
}

/*
GetAPIProjectsOK describes a response with status code 200, with default header values.

Returns a collection of project entities
*/
type GetAPIProjectsOK struct {
	Payload []*models.ProjectCollection
}

// IsSuccess returns true when this get Api projects o k response has a 2xx status code
func (o *GetAPIProjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api projects o k response has a 3xx status code
func (o *GetAPIProjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api projects o k response has a 4xx status code
func (o *GetAPIProjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api projects o k response has a 5xx status code
func (o *GetAPIProjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api projects o k response a status code equal to that given
func (o *GetAPIProjectsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPIProjectsOK) Error() string {
	return fmt.Sprintf("[GET /api/projects][%d] getApiProjectsOK  %+v", 200, o.Payload)
}

func (o *GetAPIProjectsOK) String() string {
	return fmt.Sprintf("[GET /api/projects][%d] getApiProjectsOK  %+v", 200, o.Payload)
}

func (o *GetAPIProjectsOK) GetPayload() []*models.ProjectCollection {
	return o.Payload
}

func (o *GetAPIProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
