// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIProjectsIDRatesParams creates a new GetAPIProjectsIDRatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIProjectsIDRatesParams() *GetAPIProjectsIDRatesParams {
	return &GetAPIProjectsIDRatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIProjectsIDRatesParamsWithTimeout creates a new GetAPIProjectsIDRatesParams object
// with the ability to set a timeout on a request.
func NewGetAPIProjectsIDRatesParamsWithTimeout(timeout time.Duration) *GetAPIProjectsIDRatesParams {
	return &GetAPIProjectsIDRatesParams{
		timeout: timeout,
	}
}

// NewGetAPIProjectsIDRatesParamsWithContext creates a new GetAPIProjectsIDRatesParams object
// with the ability to set a context for a request.
func NewGetAPIProjectsIDRatesParamsWithContext(ctx context.Context) *GetAPIProjectsIDRatesParams {
	return &GetAPIProjectsIDRatesParams{
		Context: ctx,
	}
}

// NewGetAPIProjectsIDRatesParamsWithHTTPClient creates a new GetAPIProjectsIDRatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIProjectsIDRatesParamsWithHTTPClient(client *http.Client) *GetAPIProjectsIDRatesParams {
	return &GetAPIProjectsIDRatesParams{
		HTTPClient: client,
	}
}

/*
GetAPIProjectsIDRatesParams contains all the parameters to send to the API endpoint

	for the get API projects ID rates operation.

	Typically these are written to a http.Request.
*/
type GetAPIProjectsIDRatesParams struct {

	/* ID.

	   The project whose rates will be returned
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API projects ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIProjectsIDRatesParams) WithDefaults() *GetAPIProjectsIDRatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API projects ID rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIProjectsIDRatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) WithTimeout(timeout time.Duration) *GetAPIProjectsIDRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) WithContext(ctx context.Context) *GetAPIProjectsIDRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) WithHTTPClient(client *http.Client) *GetAPIProjectsIDRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) WithID(id int64) *GetAPIProjectsIDRatesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API projects ID rates params
func (o *GetAPIProjectsIDRatesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIProjectsIDRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
