// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// NewPostAPIProjectsParams creates a new PostAPIProjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIProjectsParams() *PostAPIProjectsParams {
	return &PostAPIProjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIProjectsParamsWithTimeout creates a new PostAPIProjectsParams object
// with the ability to set a timeout on a request.
func NewPostAPIProjectsParamsWithTimeout(timeout time.Duration) *PostAPIProjectsParams {
	return &PostAPIProjectsParams{
		timeout: timeout,
	}
}

// NewPostAPIProjectsParamsWithContext creates a new PostAPIProjectsParams object
// with the ability to set a context for a request.
func NewPostAPIProjectsParamsWithContext(ctx context.Context) *PostAPIProjectsParams {
	return &PostAPIProjectsParams{
		Context: ctx,
	}
}

// NewPostAPIProjectsParamsWithHTTPClient creates a new PostAPIProjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIProjectsParamsWithHTTPClient(client *http.Client) *PostAPIProjectsParams {
	return &PostAPIProjectsParams{
		HTTPClient: client,
	}
}

/*
PostAPIProjectsParams contains all the parameters to send to the API endpoint

	for the post API projects operation.

	Typically these are written to a http.Request.
*/
type PostAPIProjectsParams struct {

	// Body.
	Body *models.ProjectEditForm

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProjectsParams) WithDefaults() *PostAPIProjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API projects params
func (o *PostAPIProjectsParams) WithTimeout(timeout time.Duration) *PostAPIProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API projects params
func (o *PostAPIProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API projects params
func (o *PostAPIProjectsParams) WithContext(ctx context.Context) *PostAPIProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API projects params
func (o *PostAPIProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API projects params
func (o *PostAPIProjectsParams) WithHTTPClient(client *http.Client) *PostAPIProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API projects params
func (o *PostAPIProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API projects params
func (o *PostAPIProjectsParams) WithBody(body *models.ProjectEditForm) *PostAPIProjectsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API projects params
func (o *PostAPIProjectsParams) SetBody(body *models.ProjectEditForm) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
