// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// PostAPIProjectsReader is a Reader for the PostAPIProjects structure.
type PostAPIProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIProjectsOK creates a PostAPIProjectsOK with default headers values
func NewPostAPIProjectsOK() *PostAPIProjectsOK {
	return &PostAPIProjectsOK{}
}

/*
PostAPIProjectsOK describes a response with status code 200, with default header values.

Returns the new created project
*/
type PostAPIProjectsOK struct {
	Payload *models.ProjectEntity
}

// IsSuccess returns true when this post Api projects o k response has a 2xx status code
func (o *PostAPIProjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api projects o k response has a 3xx status code
func (o *PostAPIProjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api projects o k response has a 4xx status code
func (o *PostAPIProjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api projects o k response has a 5xx status code
func (o *PostAPIProjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api projects o k response a status code equal to that given
func (o *PostAPIProjectsOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAPIProjectsOK) Error() string {
	return fmt.Sprintf("[POST /api/projects][%d] postApiProjectsOK  %+v", 200, o.Payload)
}

func (o *PostAPIProjectsOK) String() string {
	return fmt.Sprintf("[POST /api/projects][%d] postApiProjectsOK  %+v", 200, o.Payload)
}

func (o *PostAPIProjectsOK) GetPayload() *models.ProjectEntity {
	return o.Payload
}

func (o *PostAPIProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
