// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/decentral1se/go-kimai/models"
)

// DeleteAPITeamsIDProjectsProjectIDReader is a Reader for the DeleteAPITeamsIDProjectsProjectID structure.
type DeleteAPITeamsIDProjectsProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPITeamsIDProjectsProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPITeamsIDProjectsProjectIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPITeamsIDProjectsProjectIDOK creates a DeleteAPITeamsIDProjectsProjectIDOK with default headers values
func NewDeleteAPITeamsIDProjectsProjectIDOK() *DeleteAPITeamsIDProjectsProjectIDOK {
	return &DeleteAPITeamsIDProjectsProjectIDOK{}
}

/*
DeleteAPITeamsIDProjectsProjectIDOK describes a response with status code 200, with default header values.

Removes a project from the team.
*/
type DeleteAPITeamsIDProjectsProjectIDOK struct {
	Payload *models.Team
}

// IsSuccess returns true when this delete Api teams Id projects project Id o k response has a 2xx status code
func (o *DeleteAPITeamsIDProjectsProjectIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api teams Id projects project Id o k response has a 3xx status code
func (o *DeleteAPITeamsIDProjectsProjectIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api teams Id projects project Id o k response has a 4xx status code
func (o *DeleteAPITeamsIDProjectsProjectIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api teams Id projects project Id o k response has a 5xx status code
func (o *DeleteAPITeamsIDProjectsProjectIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api teams Id projects project Id o k response a status code equal to that given
func (o *DeleteAPITeamsIDProjectsProjectIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteAPITeamsIDProjectsProjectIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/teams/{id}/projects/{projectId}][%d] deleteApiTeamsIdProjectsProjectIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPITeamsIDProjectsProjectIDOK) String() string {
	return fmt.Sprintf("[DELETE /api/teams/{id}/projects/{projectId}][%d] deleteApiTeamsIdProjectsProjectIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPITeamsIDProjectsProjectIDOK) GetPayload() *models.Team {
	return o.Payload
}

func (o *DeleteAPITeamsIDProjectsProjectIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Team)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
