// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// DeleteAPITeamsIDActivitiesActivityIDReader is a Reader for the DeleteAPITeamsIDActivitiesActivityID structure.
type DeleteAPITeamsIDActivitiesActivityIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPITeamsIDActivitiesActivityIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPITeamsIDActivitiesActivityIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPITeamsIDActivitiesActivityIDOK creates a DeleteAPITeamsIDActivitiesActivityIDOK with default headers values
func NewDeleteAPITeamsIDActivitiesActivityIDOK() *DeleteAPITeamsIDActivitiesActivityIDOK {
	return &DeleteAPITeamsIDActivitiesActivityIDOK{}
}

/*
DeleteAPITeamsIDActivitiesActivityIDOK describes a response with status code 200, with default header values.

Removes a activity from the team.
*/
type DeleteAPITeamsIDActivitiesActivityIDOK struct {
	Payload *models.Team
}

// IsSuccess returns true when this delete Api teams Id activities activity Id o k response has a 2xx status code
func (o *DeleteAPITeamsIDActivitiesActivityIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api teams Id activities activity Id o k response has a 3xx status code
func (o *DeleteAPITeamsIDActivitiesActivityIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api teams Id activities activity Id o k response has a 4xx status code
func (o *DeleteAPITeamsIDActivitiesActivityIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api teams Id activities activity Id o k response has a 5xx status code
func (o *DeleteAPITeamsIDActivitiesActivityIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api teams Id activities activity Id o k response a status code equal to that given
func (o *DeleteAPITeamsIDActivitiesActivityIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteAPITeamsIDActivitiesActivityIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/teams/{id}/activities/{activityId}][%d] deleteApiTeamsIdActivitiesActivityIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPITeamsIDActivitiesActivityIDOK) String() string {
	return fmt.Sprintf("[DELETE /api/teams/{id}/activities/{activityId}][%d] deleteApiTeamsIdActivitiesActivityIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPITeamsIDActivitiesActivityIDOK) GetPayload() *models.Team {
	return o.Payload
}

func (o *DeleteAPITeamsIDActivitiesActivityIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Team)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
