// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPITeamsIDMembersUserIDParams creates a new DeleteAPITeamsIDMembersUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPITeamsIDMembersUserIDParams() *DeleteAPITeamsIDMembersUserIDParams {
	return &DeleteAPITeamsIDMembersUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPITeamsIDMembersUserIDParamsWithTimeout creates a new DeleteAPITeamsIDMembersUserIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPITeamsIDMembersUserIDParamsWithTimeout(timeout time.Duration) *DeleteAPITeamsIDMembersUserIDParams {
	return &DeleteAPITeamsIDMembersUserIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPITeamsIDMembersUserIDParamsWithContext creates a new DeleteAPITeamsIDMembersUserIDParams object
// with the ability to set a context for a request.
func NewDeleteAPITeamsIDMembersUserIDParamsWithContext(ctx context.Context) *DeleteAPITeamsIDMembersUserIDParams {
	return &DeleteAPITeamsIDMembersUserIDParams{
		Context: ctx,
	}
}

// NewDeleteAPITeamsIDMembersUserIDParamsWithHTTPClient creates a new DeleteAPITeamsIDMembersUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPITeamsIDMembersUserIDParamsWithHTTPClient(client *http.Client) *DeleteAPITeamsIDMembersUserIDParams {
	return &DeleteAPITeamsIDMembersUserIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPITeamsIDMembersUserIDParams contains all the parameters to send to the API endpoint

	for the delete API teams ID members user ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPITeamsIDMembersUserIDParams struct {

	/* ID.

	   The team from which the member will be removed
	*/
	ID int64

	/* UserID.

	   The team member to remove (User ID)
	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API teams ID members user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITeamsIDMembersUserIDParams) WithDefaults() *DeleteAPITeamsIDMembersUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API teams ID members user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITeamsIDMembersUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) WithTimeout(timeout time.Duration) *DeleteAPITeamsIDMembersUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) WithContext(ctx context.Context) *DeleteAPITeamsIDMembersUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) WithHTTPClient(client *http.Client) *DeleteAPITeamsIDMembersUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) WithID(id int64) *DeleteAPITeamsIDMembersUserIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) SetID(id int64) {
	o.ID = id
}

// WithUserID adds the userID to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) WithUserID(userID int64) *DeleteAPITeamsIDMembersUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete API teams ID members user ID params
func (o *DeleteAPITeamsIDMembersUserIDParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPITeamsIDMembersUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
