// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPITeamsIDParams creates a new GetAPITeamsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPITeamsIDParams() *GetAPITeamsIDParams {
	return &GetAPITeamsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPITeamsIDParamsWithTimeout creates a new GetAPITeamsIDParams object
// with the ability to set a timeout on a request.
func NewGetAPITeamsIDParamsWithTimeout(timeout time.Duration) *GetAPITeamsIDParams {
	return &GetAPITeamsIDParams{
		timeout: timeout,
	}
}

// NewGetAPITeamsIDParamsWithContext creates a new GetAPITeamsIDParams object
// with the ability to set a context for a request.
func NewGetAPITeamsIDParamsWithContext(ctx context.Context) *GetAPITeamsIDParams {
	return &GetAPITeamsIDParams{
		Context: ctx,
	}
}

// NewGetAPITeamsIDParamsWithHTTPClient creates a new GetAPITeamsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPITeamsIDParamsWithHTTPClient(client *http.Client) *GetAPITeamsIDParams {
	return &GetAPITeamsIDParams{
		HTTPClient: client,
	}
}

/*
GetAPITeamsIDParams contains all the parameters to send to the API endpoint

	for the get API teams ID operation.

	Typically these are written to a http.Request.
*/
type GetAPITeamsIDParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API teams ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITeamsIDParams) WithDefaults() *GetAPITeamsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API teams ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITeamsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API teams ID params
func (o *GetAPITeamsIDParams) WithTimeout(timeout time.Duration) *GetAPITeamsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API teams ID params
func (o *GetAPITeamsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API teams ID params
func (o *GetAPITeamsIDParams) WithContext(ctx context.Context) *GetAPITeamsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API teams ID params
func (o *GetAPITeamsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API teams ID params
func (o *GetAPITeamsIDParams) WithHTTPClient(client *http.Client) *GetAPITeamsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API teams ID params
func (o *GetAPITeamsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API teams ID params
func (o *GetAPITeamsIDParams) WithID(id string) *GetAPITeamsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API teams ID params
func (o *GetAPITeamsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPITeamsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
