// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/decentral1se/go-kimai/models"
)

// NewPatchAPITeamsIDParams creates a new PatchAPITeamsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPITeamsIDParams() *PatchAPITeamsIDParams {
	return &PatchAPITeamsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPITeamsIDParamsWithTimeout creates a new PatchAPITeamsIDParams object
// with the ability to set a timeout on a request.
func NewPatchAPITeamsIDParamsWithTimeout(timeout time.Duration) *PatchAPITeamsIDParams {
	return &PatchAPITeamsIDParams{
		timeout: timeout,
	}
}

// NewPatchAPITeamsIDParamsWithContext creates a new PatchAPITeamsIDParams object
// with the ability to set a context for a request.
func NewPatchAPITeamsIDParamsWithContext(ctx context.Context) *PatchAPITeamsIDParams {
	return &PatchAPITeamsIDParams{
		Context: ctx,
	}
}

// NewPatchAPITeamsIDParamsWithHTTPClient creates a new PatchAPITeamsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPITeamsIDParamsWithHTTPClient(client *http.Client) *PatchAPITeamsIDParams {
	return &PatchAPITeamsIDParams{
		HTTPClient: client,
	}
}

/*
PatchAPITeamsIDParams contains all the parameters to send to the API endpoint

	for the patch API teams ID operation.

	Typically these are written to a http.Request.
*/
type PatchAPITeamsIDParams struct {

	// Body.
	Body *models.TeamEditForm

	/* ID.

	   Team ID to update
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API teams ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITeamsIDParams) WithDefaults() *PatchAPITeamsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API teams ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPITeamsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API teams ID params
func (o *PatchAPITeamsIDParams) WithTimeout(timeout time.Duration) *PatchAPITeamsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API teams ID params
func (o *PatchAPITeamsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API teams ID params
func (o *PatchAPITeamsIDParams) WithContext(ctx context.Context) *PatchAPITeamsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API teams ID params
func (o *PatchAPITeamsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API teams ID params
func (o *PatchAPITeamsIDParams) WithHTTPClient(client *http.Client) *PatchAPITeamsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API teams ID params
func (o *PatchAPITeamsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API teams ID params
func (o *PatchAPITeamsIDParams) WithBody(body *models.TeamEditForm) *PatchAPITeamsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API teams ID params
func (o *PatchAPITeamsIDParams) SetBody(body *models.TeamEditForm) {
	o.Body = body
}

// WithID adds the id to the patch API teams ID params
func (o *PatchAPITeamsIDParams) WithID(id int64) *PatchAPITeamsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API teams ID params
func (o *PatchAPITeamsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPITeamsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
