// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"decentral1se/go-kimai/models"
)

// PostAPITeamsIDMembersUserIDReader is a Reader for the PostAPITeamsIDMembersUserID structure.
type PostAPITeamsIDMembersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPITeamsIDMembersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPITeamsIDMembersUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPITeamsIDMembersUserIDOK creates a PostAPITeamsIDMembersUserIDOK with default headers values
func NewPostAPITeamsIDMembersUserIDOK() *PostAPITeamsIDMembersUserIDOK {
	return &PostAPITeamsIDMembersUserIDOK{}
}

/*
PostAPITeamsIDMembersUserIDOK describes a response with status code 200, with default header values.

Adds a new user to a team.
*/
type PostAPITeamsIDMembersUserIDOK struct {
	Payload *models.Team
}

// IsSuccess returns true when this post Api teams Id members user Id o k response has a 2xx status code
func (o *PostAPITeamsIDMembersUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api teams Id members user Id o k response has a 3xx status code
func (o *PostAPITeamsIDMembersUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api teams Id members user Id o k response has a 4xx status code
func (o *PostAPITeamsIDMembersUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api teams Id members user Id o k response has a 5xx status code
func (o *PostAPITeamsIDMembersUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api teams Id members user Id o k response a status code equal to that given
func (o *PostAPITeamsIDMembersUserIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAPITeamsIDMembersUserIDOK) Error() string {
	return fmt.Sprintf("[POST /api/teams/{id}/members/{userId}][%d] postApiTeamsIdMembersUserIdOK  %+v", 200, o.Payload)
}

func (o *PostAPITeamsIDMembersUserIDOK) String() string {
	return fmt.Sprintf("[POST /api/teams/{id}/members/{userId}][%d] postApiTeamsIdMembersUserIdOK  %+v", 200, o.Payload)
}

func (o *PostAPITeamsIDMembersUserIDOK) GetPayload() *models.Team {
	return o.Payload
}

func (o *PostAPITeamsIDMembersUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Team)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
