// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPITagsIDReader is a Reader for the DeleteAPITagsID structure.
type DeleteAPITagsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPITagsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPITagsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPITagsIDNoContent creates a DeleteAPITagsIDNoContent with default headers values
func NewDeleteAPITagsIDNoContent() *DeleteAPITagsIDNoContent {
	return &DeleteAPITagsIDNoContent{}
}

/*
DeleteAPITagsIDNoContent describes a response with status code 204, with default header values.

HTTP code 204 for a successful delete
*/
type DeleteAPITagsIDNoContent struct {
}

// IsSuccess returns true when this delete Api tags Id no content response has a 2xx status code
func (o *DeleteAPITagsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api tags Id no content response has a 3xx status code
func (o *DeleteAPITagsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api tags Id no content response has a 4xx status code
func (o *DeleteAPITagsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api tags Id no content response has a 5xx status code
func (o *DeleteAPITagsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api tags Id no content response a status code equal to that given
func (o *DeleteAPITagsIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteAPITagsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/tags/{id}][%d] deleteApiTagsIdNoContent ", 204)
}

func (o *DeleteAPITagsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/tags/{id}][%d] deleteApiTagsIdNoContent ", 204)
}

func (o *DeleteAPITagsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
