// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectRateForm project rate form
//
// swagger:model ProjectRateForm
type ProjectRateForm struct {

	// The internal rate (eg. 10.0 or 10)
	InternalRate float64 `json:"internalRate,omitempty"`

	// If "true" each time record gets the same rate, regardless of its duration
	IsFixed bool `json:"isFixed,omitempty"`

	// The rate (eg. 10.5)
	// Required: true
	Rate *float64 `json:"rate"`

	// User ID
	User int64 `json:"user,omitempty"`
}

// Validate validates this project rate form
func (m *ProjectRateForm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectRateForm) validateRate(formats strfmt.Registry) error {

	if err := validate.Required("rate", "body", m.Rate); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this project rate form based on context it is used
func (m *ProjectRateForm) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectRateForm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectRateForm) UnmarshalBinary(b []byte) error {
	var res ProjectRateForm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
